added moderator badges for our staff in the forums
trailbehind/NG_Help_Center pull request #6
Opened 2019-04-30 02:00 UTC by ChrisHillGaia

Creating a draft pr bc this still isn't 100% and I need some help. 

What it does: Gives a 'Support Staff' badge to Ashli, me, Robyn, and Nate when they post to the community forum. 

What it needs to do before complete:
1. use unique user id instead of names to apply the moderator tag
2. add Andrew, Erik, Torrey, (maybe Corey) 
3. enable the js to allow for more than one class of mod (ie, Staff Support, Support Manager, CEO)

2019-04-30 02:01 UTC, ChrisHillGaia commented
https://trello.com/c/tTHyBGn9/258-add-forum-tags

2019-04-30 15:05 UTC, ashlibaldwin commented
you can find user ids for people in zendesk profile urls. here's yours:
https://gaiagpshelp.zendesk.com/agent/users/**362154083768**/assigned_tickets

Do you have a sandbox setup where I can view this so far?

2019-04-30 18:14 UTC, ChrisHillGaia commented
2. This is actually how it's already set up. 

3. gaiagpshelp1556318683.zendesk.com

2019-04-30 18:17 UTC, ChrisHillGaia commented
Do we _need_ more than one kind of mod badge? 
- bc if we don't, it's much simpler. What I have built here will work, and I can even parse it down more. 
- if we do, we will need to hard code each new agent into the js. 
-- but this would also allow us to have "support staff, support manager, CEO, developer, etc."

2019-04-30 22:18 UTC, ashlibaldwin commented on script.js
> +
remove blank line? this file should have no changes

2019-04-30 22:18 UTC, ashlibaldwin commented on style.css
> +.moderator:after, .support-manager:after {
AFAICT `support-manager` is not being used anywhere

2019-04-30 22:19 UTC, ashlibaldwin commented on style.css
> +content: "Support Staff";
Lets make this says 'Gaia GPS Staff' or 'Gaia GPS Support'

2019-04-30 22:19 UTC, ashlibaldwin commented on style.css
> +
you don't need a blank line after every attribute - lets remove those

2019-04-30 22:20 UTC, ashlibaldwin requested changes
please see requested changes

2019-05-01 15:09 UTC, ashlibaldwin commented on script.js
> +
The blank line is still showing here. you can view the diff on your PR here https://github.com/trailbehind/NG_Help_Center/pull/6/files

2019-05-01 20:25 UTC, ashlibaldwin approved these changes

2019-05-02 22:16 UTC, merged